"""
Django settings for p7 project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^pxui41@j26x%)!9bgbwljhi!32xfj(nh2a2tsv=utx2ls2)zu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',  # Creates default tables which we do not want
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    # "repository.apps.RepositoryConfig",
    "repository",
    "django_q",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
]

# CORS: allow Next.js origins
ALLOWED_HOSTS = [
    "localhost", 
    "api.localhost",
    "127.0.0.1", 
    "130.225.39.162", 
    "backend", 
    "frontend"
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost", 
    "https://localhost", 
    "http://api.localhost",
    "https://api.localhost",
    "http://127.0.0.1",
    "https://127.0.0.1",
    "http://130.225.39.162",
    "https://130.225.39.162",
    "http://frontend:3000", 
    "https://frontend:3000", 
    "http://backend:8000", 
    "https://backend:8000",
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost", 
    "https://localhost", 
    "http://api.localhost",
    "https://api.localhost",
    "http://127.0.0.1",
    "https://127.0.0.1",
    "http://130.225.39.162",
    "https://130.225.39.162",
    "http://frontend:3000", 
    "https://frontend:3000", 
    "http://backend:8000", 
    "https://backend:8000",
]

ROOT_URLCONF = 'p7.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'p7.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DATABASE_ENGINE"),
        "NAME": os.getenv("DATABASE_NAME"),
        "USER": os.getenv("DATABASE_USERNAME"),
        "PASSWORD": os.getenv("DATABASE_PASSWORD"),
        "HOST": os.getenv("DATABASE_HOST"),
        "PORT": os.getenv("DATABASE_PORT"),
    }
}
# DJANGO_Q database config. Docs: https://django-q2.readthedocs.io/en/master/configure.html
Q_CLUSTER = {
    'name': 'default',
    'retry': 3600,
    'timeout': 600,
    'recycle': 250,
    'save_limit': 10,
    'queue_limit': 100,
    'cpu_affinity': 1,
    'label': 'Django Q2',
    'orm': 'default',
}




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

""" AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
] """


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'da-dk'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-MIGRATION_MODULES
""" MIGRATION_MODULES = {
    "repository": None,             # <- Name for repo we should not create migrations for
} """

APPEND_SLASH = True  # Ensure trailing slashes are appended to URLs

